services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana

  grafana-dev:
    image: ghcr.io/volkovlabs/app:latest
    entrypoint: /run.sh
    ports:
      - 3000:3000/tcp
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/panels.json
      - GF_INSTALL_PLUGINS=volkovlabs-rss-datasource,marcusolsson-static-datasource,yesoreyeram-infinity-datasource
    volumes:
      - ./dist:/var/lib/grafana/plugins/marcusolsson-dynamictext-panel
      - ./provisioning:/etc/grafana/provisioning
    profiles:
      - dev

  grafana-main:
    image: grafana/grafana:main
    ports:
      - 3000:3000/tcp
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_USERS_DEFAULT_THEME=light
      - GF_INSTALL_PLUGINS=marcusolsson-static-datasource,volkovlabs-rss-datasource,yesoreyeram-infinity-datasource
    volumes:
      - ./dist:/var/lib/grafana/plugins/marcusolsson-dynamictext-panel
      - ./provisioning:/etc/grafana/provisioning
    profiles:
      - main

  grafana-dep:
    image: grafana/grafana:11.6.9@sha256:8dbbae5093f40e622c66f7f96862f76bdb3764fcffc727ad9952ad5d1ed79f79
    ports:
      - 3000:3000/tcp
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_USERS_DEFAULT_THEME=light
      - GF_INSTALL_PLUGINS=volkovlabs-rss-datasource,marcusolsson-static-datasource,yesoreyeram-infinity-datasource
    volumes:
      - ./dist:/var/lib/grafana/plugins/marcusolsson-dynamictext-panel
      - ./provisioning:/etc/grafana/provisioning
    profiles:
      - dependency

  playwright:
    build:
      context: .
      dockerfile: test/Dockerfile
    environment:
      - GRAFANA_URL=http://grafana:3000
    volumes:
      - ./test:/app/test
      - ./playwright-report:/app/playwright-report
    depends_on:
      grafana:
        condition: service_healthy
    profiles:
      - e2e
      - playwright
